version: "3"
services:
  web:    
    build: ./NetworkSite
    ports:
      - "5000:80"    
    depends_on:
      - "webapi"
  scanner:    
    build: ./NetworkScanner
    depends_on:
      - "webapi"
      - "redis"
  webapi:
    build: ./NetworkService
    ports:
      - "5001:80"
  redis:
    image: "redis:alpine"