version: "3"
services:
  redis:
    image: "redis:alpine"
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
  web:    
    build: ./NetworkSite
    ports:
      - "5000:80"    
    depends_on:
      - "webapi"
  webapi:
    build: ./NetworkService
    ports:
      - "5001:80"
  scanner:    
    build: ./NetworkScanner
    depends_on:
      - "webapi"
      - "rabbitmq"  
  receiver:    
    build: ./NetworkHostedServices
    depends_on:
      - "webapi"
      - "redis"
      - "rabbitmq"